title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
      Buttons are only needed in the image-card (whenever it get hovered). It will allow the person to view a specific artwork.
    fields:
      - name: url
        type: url
        example: "/for-fun-page/"
        required: false
      - name: url
        type: url
        example: "/broadcast-package/"
        required: false
